version: '3.0'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    networks:
      - laravel

  php:
    networks:
      - laravel
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
